root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test\\.go$"]
  send_interrupt = true
  kill_delay = 500
