[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-10
monitor_port = /dev/cu.usbserial-10
lib_deps =
  knolleary/PubSubClient @ ^2.8
