[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient @ ^2.8
  miguelbalboa/MFRC522 @ ^1.4.10
  arduino-libraries/Arduino_CryptoLibrary @ ^1.0.0
